- name: Setup ubuntu common-slaves instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    openstack_names: 
      - xxx-ansibletest-1
    openstack_tap_role: tapjenkins-ubuntu-ansible
  roles:
    - openstack

- name: Configure machines
  hosts: role_tapjenkins-ubuntu-ansible
  remote_user: ubuntu
  sudo: yes
  vars:
    swarm_slave_labels: "ubuntu-ansible"
    swarm_slave_executors_count: 4
    update_dns_zone: "tap.internal"
  roles:
    - role: update-dns
      sudo: no

    - role: telerik-certificate-authority

    - role: dns-client

    - role: ubuntu-swarm-slave
      tags: ubuntu-swarm-slave

    - role: ansible-runner
      tags: ansible-runner